### ISSUE TITLE
Error in Covars[, i] - min(Covars[, i]);

### ISSUE THREAD

**Issue by ekopylova** [syspremed/exploBATCH#4]
Hello!

I successfully installed your tool and ran the following example from your manual:

```
expBATCH(D=Breast,batchCL=batchBreast,Conf=NA, mindim=2, maxdim=9,method="ppcca", SDselect=2)
```

However, when I tried using my own matrix (```D```) and ```batchCL```, the following error was given:

```
Error in Covars[, i] - min(Covars[, i]) : 
  non-numeric argument to binary operator
```

It appears I did get the complete folder ```pcaBeforeCorrection``` but all subsequent folders are empty.

Should I preprocess my matrix prior to passing it to  ```expBATCH```? For example, log transformation, scaling, outlier removal, or are these steps all performed when calling ```expBATCH```?

Thanks for any input!
Jenya

**Comment by gnyamundanda** [comment]
Hi Jenya

I am forwarding you query to Gift who will help you to address this.

Thanks,

Anguraj

**Comment by ekopylova** [comment]
Thanks @gnyamundanda !

In fact, I have been able to run the code after updating some packages (primarily updating ```gfortran``` to the official, most recent version).

Based on the results in your paper, ```correctBATCH``` results generally correlated well with ```ComBat``` (~0.95 Pearson correlation for the two datasets you tested). In my dataset, ```ComBat``` did not appear to remove the batch effect significantly, but ```correctBATCH``` yes (see plots below). Their correlation is 0.72.

Firstly, do you have suggestions for why these results differ so much? I'm very happy to see the batch effect removed completely by ```correctBATCH```, but would be great to understand the reasoning. I'm using untargeted metabolomics LC-MS data.

Secondly, is it possible for the ```expBATCH``` function to output the corrected PCA scores & loadings into a variable? Currently only PCA scores after correction are output directly to a file. Is it also possible to output the corrected / normalized data matrix ```D``` to allow downstream analyses?

Thanks!

```PCA``` before batch correction
![pcaBeforeCorrection](https://user-images.githubusercontent.com/6933444/82049116-1c3a0480-96b6-11ea-821d-7f59ff9b19ee.png)

```FindBATCH``` Forest plot before batch correction
![BatchEffect](https://user-images.githubusercontent.com/6933444/82050330-3ffe4a00-96b8-11ea-9df9-c8f08cb7cdb2.png)

```ComBat``` PCA plot after batch correction
![pca_After_Combat_Correction](https://user-images.githubusercontent.com/6933444/82049216-3e338700-96b6-11ea-9857-4a7ed4d8d4f2.png)
```ComBat``` Forest plot after batch correction (6 batches)
![BatchEffectComBat](https://user-images.githubusercontent.com/6933444/82048902-bd748b00-96b5-11ea-9d84-16a894aad769.png)

```correctBATCH``` PCA plot after batch correction
![2020-05-15_pca_After_PPCCA_correction](https://user-images.githubusercontent.com/6933444/82049316-64f1bd80-96b6-11ea-878c-d2f0195184fb.png)

```correctBATCH``` Forest plot after batch correction (6 batches)
![BatchEffect_CorrectBATCH](https://user-images.githubusercontent.com/6933444/82048925-c7968980-96b5-11ea-9048-232d2ed09096.png)

**Comment by gnyamundanda** [comment]
Hi Jenya,

Like we have shown in the paper, in most cases combat and correctBATCH perfomance are comparable. However, they are different batch correction approachs. ComBat is  an empirical Bayes method based on location/scale batch adjustments whilst correctBATCH removes batch effect on each affected probabilistic principal component (pPC). So you expect some differences in the their results. However, in this case its surprising that ComBat failed to correct any batch effect at all. If you compare the plots of pca before correction and after ComBat correction, and also associated forest plots, they look almost identical, suggesting that ComBat correction is not doing anything to the data. 

ComBat assumes genes are independent of each other, hence, corrects batch effect on each gene seperately from the other genes. However, this is a strong assumption, some genes are correlated (forming gene clusters) and these gene clusters can be affected by bach effect differently from the other gene clusters. Instead, by estimating and correcting for batch effect on each pPC, correctBATCH estimates joint batch effect and correct for it on each gene cluster.   

However, another issue to consider is, ComBat perfomance depends on the choice of batch effect prior distribution. In exploBATCH, ComBat is set on its default settings, so its using parametric prior. Hence, its worth repeating this analysis using its non-parametric prior on batch effect. 

Otherwise, for the second question, the output of correctBATCH can be found in correctBATCH folder and the file is named 'ppccaCorrectedData.txt'.

Thanks.

**Comment by ekopylova** [comment]
Thanks for your reply. 'ppccaCorrectedData.txt' is exactly what I was looking for. Unfortunately parametric or non-parametric setting reproduces the same result for ComBat (I also ran the program stand-alone), therefore it is not an issue with parameter setting in ```expBATCH```.
